/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Entry } from "./Entry";
import { EntryCountArgs } from "./EntryCountArgs";
import { EntryFindManyArgs } from "./EntryFindManyArgs";
import { EntryFindUniqueArgs } from "./EntryFindUniqueArgs";
import { DeleteEntryArgs } from "./DeleteEntryArgs";
import { EntryService } from "../entry.service";
@graphql.Resolver(() => Entry)
export class EntryResolverBase {
  constructor(protected readonly service: EntryService) {}

  async _entriesMeta(
    @graphql.Args() args: EntryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Entry])
  async entries(@graphql.Args() args: EntryFindManyArgs): Promise<Entry[]> {
    return this.service.entries(args);
  }

  @graphql.Query(() => Entry, { nullable: true })
  async entry(
    @graphql.Args() args: EntryFindUniqueArgs
  ): Promise<Entry | null> {
    const result = await this.service.entry(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Entry)
  async deleteEntry(
    @graphql.Args() args: DeleteEntryArgs
  ): Promise<Entry | null> {
    try {
      return await this.service.deleteEntry(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
